develop_topic_task:
  description: >
    You are tasked with developing Python code for {topic}.
    Previous execution logs : {logs}
    Donot change the overall structure of the code, only fix the bugs and errors.
    Write clean, efficient, and well-documented Python code.
    Include docstrings and type hints where appropriate.
    Also include logging in the code wherever appropriate.
  expected_output: >
    Python implementation of the requested functionality
  agent: developer

write_unit_tests_task:
  description: >
    Write comprehensive unit tests for the code implementing {topic}.
    The code is available in the codebase.py file.
    Ensure:
    1. All functions are tested
    2. Edge cases are covered
    3. Tests are well-documented
    4. Logging is included in the tests
  expected_output: >
    Complete set of unit tests for the implementation
  agent: tester

execute_unit_tests_task:
  description: >
    Execute the unit tests by running the execute_test.py file.
    This file will:
    1. Load your solution from codebase.py
    2. Execute it using the test_execution function from test_cases.py
    3. Report whether the tests passed or failed
    
    Run the file using: python execute_test.py
    
    Important: The first line of your output must start with either:
    "result: Passed" - if all tests pass
    "result: Failed" - if any test fails
    Follow this with detailed test execution results.
  expected_output: >
    Test execution results with pass/fail status
  agent: executor

exit_task:
  description: >
    Check the test execution results in tests_results.md.
    Return:
    - True if the first line contains "result: Passed"
    - False if the first line contains "result: Failed"
    This will determine if the crew should exit or continue development.
  expected_output: >
    Boolean indicating whether all tests passed
  agent: exit_agent
