write_unit_tests_task:
  description: >
    Write unit tests for {topic}
    Make sure you write unit tests for all the functions and methods in the codebase.
  expected_output: >
    A list of unit tests for {topic}
  agent: tester

execute_unit_tests_task:
  description: >
    Execute unit tests for {topic}
    Make sure you execute all the unit tests for {topic}.
  expected_output: >
    A list of results for the unit tests for {topic}, and a single word summary at the top
    "result: Passed" if all tests passed or "result: Failed" if any tests failed
  agent: executor

develop_topic_task:
  description: >
    Develop {topic}
    Make sure you develop {topic} given the requirements and {logs} for known issues.
  expected_output: >
    The fully developed {topic}
  agent: developer

exit_task:
  description: >
    Exit the crew
  agent: exit_agent
